name: 'action-cc-reporter'
description: 'This action allows you to upload coverage report to [_Code Climate_](https://codeclimate.com/).'
inputs:
  format:
    description: 'Format of the coverage report to upload'
    required: false
    default: 'lcov'
  output:
    description: 'Output file for the upload operation'
    required: false
    default: 'coverage/codeclimate.json'
  report:
    description: 'Report file to upload'
    required: false
    default: 'coverage/lcov.info'
env:
  CC_TEST_REPORTER_ID:
    description: 'Code Climate reporter ID'
    required: true
  GIT_BRANCH:
    description: 'Branch that the coverage report refers to'
    required: true
  GIT_COMMIT:
    description: 'Commit SHA that the coverage report refers to'
    required: true
runs:
  using: "composite"
  steps:
    - name: Retrieve CodeClimate reporter
      run: |
        echo "Downloading CodeClimate reporter binaries..."
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
      shell: bash
    - name: Configurate reporter
      run: |
        echo "Configurating test reporter..."
        ./cc-test-reporter format-coverage -t ${{ inputs.format }} -o ${{ inputs.output }} ${{ inputs.report }}
      shell: bash
    - name: Upload report
      run: |
        echo "Uploading reports to Code Climate..."
        ./cc-test-reporter upload-coverage
      shell: bash
    - name: Cleanup
      run: |
        echo "Removing reporter binaries..."
        rm cc-test-reporter
      shell: bash
